### PR TITLE
update forge for version 36.2.19

### PR DESCRIPTION
**Pull request by joaoespanhol**

### CODE REVIEW

**Comment by Mgazul** [comment]
You also need to change:  Rectify Forge (ae7609979)

**Comment by joaoespanhol** [comment]
> ae760997

> You also need to change: Rectify Forge (ae7609979)

thanks, done Rectify Forge: 5a2c7aa

**Comment by Mgazul** [comment]
https://github.com/MohistMC/Mohist/blob/1.16.5/build.gradle#L176

**Comment by Mgazul** [comment]
It is recommended to send the PR again

**Pull request closed without merging**
