### PR TITLE
Provide a Global Exception Handler to handle some frequently occurring Exceptions.

### PR DESCRIPTION
**Pull request by glowingstone124**
This pr added a new Handler called com.mohistmc.feature.ExceptionHandler to caught exceptions.
Some basic explanations are provided, and further improvements like i18n and more is being planned.

### CODE REVIEW

**Comment by Mgazul** [comment]
Can you provide some renderings?

**Comment by glowingstone124** [comment]
***@***.***
手动抛new异常的时候长这样，实际产出的时候会有对应的class名称
发件人: Mgazul ***@***.***>
日期: 星期五, 2024年10月11日 18:09
收件人: MohistMC/Mohist ***@***.***>
抄送: Glowingstone124 ***@***.***>, Author ***@***.***>
主题: Re: [MohistMC/Mohist] Provide a Global Exception Handler to handle some frequently occurring Exceptions. (PR #3388)

Can you provide some renderings?

―

**Comment by glowingstone124** [comment]
f35746654bcf30b365964e1d51f9f5f2
I manually thrown an exception in main method, and it looks like this.
When an exception actucally be thrown, it will display the className info.

**Comment by Mgazul** [comment]
Try throwing some exceptions in the craftbukkit or forge classes, such as the common ```NullPointerException, ArrayIndexOutOfBoundsException```, etc.

**Comment by glowingstone124** [comment]
need further dev, closing now.

**Pull request closed without merging**
