### PR TITLE
Translations Update

### PR DESCRIPTION
**Pull request by MohistBOT**
**I18N Updates**
Hello, i'm updating i18n files automatically, this system is still in beta and may have bugs. If there is any error, do not merge this.

_Goodbye!

### CODE REVIEW

**Review by Romaindu35 — CHANGES_REQUESTED** [review]
Why add lot of ```\``` ?

**Comment by Shawiizz** [comment]
This is added automatically by crowdin. I think it's to escape some specials characters, but I'm not sure if these \ are displayed in the console then.

**Comment by Romaindu35** [comment]
Ok, this need test, but this seems good for me !

**Review by Romaindu35 — APPROVED** [review]

**Comment by Shawiizz** [comment]
I close this PR, i need to fix some issues.

**Pull request closed without merging**
