### PR TITLE
feat: backport Paper changes on EntityDeathEvent

### PR DESCRIPTION
**Pull request by SNWCreations**

### CODE REVIEW

**Comment by Mgazul** [comment]
Will break mixin compatibility of some mods

**Comment by SNWCreations** [comment]
any idea on improving it?

**Comment by SNWCreations** [comment]
tried to improve mod compatibility.

**Comment by Mgazul** [comment]
Migrate a large number of PAIL protected -> public to accesstransformer.cfg

**Comment by SNWCreations** [comment]
STILL Processing
I may finish solving this tomorrow as it is so late for me, sleep time huh

**Comment by SNWCreations** [comment]
minimized the patch. avoided AT usage.

**Comment by Mgazul** [comment]
A compatibility issue occurred: Connector-1.0.0-beta.46+1.20.1 + fabric-api-0.92.2+1.11.8+1.20.1, in LivingEntity
https://github.com/Sinytra/ForgifiedFabricAPI/blob/220dc0d13f1d6cae3926eb06d542badc9e21f994/fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/LivingEntityMixin.java#L52

**Comment by SNWCreations** [comment]
will resolve it later, log please.

**Comment by SNWCreations** [comment]
Hmm it seems to be fixed? I'd glad to give it a look if required.

**Comment by Mgazul** [comment]
Yes, fixed it. https://github.com/MohistMC/Mohist/commit/f6c432987658d72a25bf7171b4a4440363dfcb28#diff-f495b73fea7159910b2b3e0cd22018163bb9fb0067bcc9f4964bf3b8190f41daR930

**Pull request merged**
