### PR TITLE
some patches / fixes

### PR DESCRIPTION
**Pull request by m1lc0lm**
Note that with the current version the server crashes, but with this the server stops loading at permission handler init from forge. i already fixed the crash with current code from github, but there where the same thing. it stops loading

### CODE REVIEW

**Review by Serega007RU — COMMENTED** [review]
Fixes with the console, does this fix only apply to 1.18.x or is it worth fixing on older versions too? I had problems on 1.12.2 with server freezing due to the console

**Comment by m1lc0lm** [comment]
> Does this problem only apply to 1.18 or to older versions too?

I submitted to to 1.18.2.  So only 1.18

**Comment by m1lc0lm** [comment]
> Fixes with the console, does this fix only apply to 1.18.x or is it worth fixing on older versions too? I had problems on 1.12.2 with server freezing due to the console

I'm sorry. No this fix only applies to 1.18.2. I dont know if it is able to fix in 1.12.2*

**Comment by m1lc0lm** [comment]
all version of 1.18.2 not work. i tested every version.
it stops loading after PermissionAPI loading

**Pull request merged**
