### PR TITLE
some patches

### PR DESCRIPTION
**Pull request by m1lc0lm**
I fixed the Nether/End Errors, removed the world patches and done some patches

### CODE REVIEW

**Comment by m1lc0lm** [comment]
Now it works fine. I tested the Nether and the End.

**Comment by Mgazul** [comment]
Do not modify the method of forge, refer to the fix method of 1.16.5

**Comment by m1lc0lm** [comment]
I had changed it, but changed it back. void is the method forge used
Screenshot_5

**Comment by m1lc0lm** [comment]
it is the same as i changed it back
Forge: https://github.com/MinecraftForge/MinecraftForge/blob/1.18.x/patches/minecraft/net/minecraft/world/entity/vehicle/Boat.java.patch

**Pull request merged**
