### PR TITLE
some patches

### PR DESCRIPTION
**Pull request by m1lc0lm**

### CODE REVIEW

**Comment by m1lc0lm** [comment]
Note: Currently the server crashes if i place any block

**Comment by m1lc0lm** [comment]
because the blockEntity is null

**Comment by m1lc0lm** [comment]
I fixed it

**Comment by m1lc0lm** [comment]
Currently the nether is not working
Error: https://haste.mohistmc.com/rizogebaya.properties

**Comment by Mgazul** [comment]
The current work only solves the number of nms-patches, do not modify any code about the world (this part of the patch is not considered to be applied, it will break the compatibility of the mod)

**Comment by m1lc0lm** [comment]
I will change the World patches to forge Standard

**Comment by m1lc0lm** [comment]
I open a new PR if the new code works

**Pull request closed without merging**
