### PR TITLE
[WIP] Add paper patch

### PR DESCRIPTION
**Pull request by Romaindu35**
I am in the process of adding the paper api / patch patches
You can see the patch being added / being added on this google doc :
https://docs.google.com/spreadsheets/d/1kecEC5bzdcP6VsAoDDa_xbzHEgj-qE3EvResmhw2Ayw/edit?usp=sharing

### !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### CODE REVIEW

**Comment by Romaindu35** [comment]
We are agree that I don't add paper metrics patch (https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0005-Paper-Metrics.patch) ?

**Comment by Shawiizz** [comment]
yes, don't add paper metrics

**Comment by Romaindu35** [comment]
> yes, don't add paper metrics

Ok

**Comment by KR33PYK1NG** [comment]
@Romaindu35, it'd be really useful if you ported [this patch](https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0375-implement-optional-per-player-mob-spawns.patch).

**Comment by Romaindu35** [comment]
I'm doing it right after the one I'm doing now 👍

**Comment by KR33PYK1NG** [comment]
How stable are these changes right now?

**Comment by Romaindu35** [comment]
This pull request is now ready to be merge

**Pull request merged**
