### PR TITLE
Update to Forge 40.0.19

### PR DESCRIPTION
**Pull request by m1lc0lm**

### CODE REVIEW

**Review by Romaindu35 — CHANGES_REQUESTED** [review]
This can be an error or there are a reason, but I can't find modify file in commit https://github.com/MinecraftForge/MinecraftForge/commit/de1050e42048fa51f6842df5866decd5f9ddd5a7 in this commit

**Comment by m1lc0lm** [comment]
I know what you mean. But some changes from newer commits of MinecraftForge were already applied in Mohist

**Comment by Romaindu35** [comment]
It missing just the line ```if (finalComponent != null)``` after here https://github.com/MohistMC/Mohist/blob/fcc989a0b1615ca87712d449d520115db1e6a6e2/patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch#L737

**Comment by Mgazul** [comment]
Please remember to modify README.md, you do not modify it every time

**Comment by m1lc0lm** [comment]
> Please remember to modify README.md, you do not modify it every time

I'll do it from now on

**Comment by m1lc0lm** [comment]
> It missing just the line `if (finalComponent != null)` after here
> 
> https://github.com/MohistMC/Mohist/blob/fcc989a0b1615ca87712d449d520115db1e6a6e2/patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch#L737

I didnt saw that sorry 😵‍💫

**Comment by Romaindu35** [comment]
No problem, MGazul add this

**Pull request merged**
